version: '1'

services:

  app:
    container_name: gestion-tasa-cambio
    build: .
    ports:
      - 9090:9090
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      -   mysqltc

  mysqltc:
    container_name: mysqltc
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: desa
    ports:
      - 5506:3306