server:
  port: ${app.port:9090}

spring:
  output:
    ansi:
      enabled: always
  application:
    name: gestion-tasa-cambio
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_ADDRESS}
management:
  endpoints:
    web:
      exposure:
        include: '*'