server:
  port: ${app.port:9090}

spring:
  output:
    ansi:
      enabled: always
  application:
    name: gestion-tasa-cambio
  profiles:
    active: ${environment.profile}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_ADDRESS}

base-datos:
    mysql:
      user: root
      password: desa
      urljdbc: jdbc:mysql://localhost:3306/dbtasas

